[package]
name = "git-commit-mine"
version = "0.1.4"
authors = ["'Gunnar Þór Magnússon' <gunnar.magnusson@booking.com>"]

[dependencies]
sha1 = "0.6.0"
structopt = "0.2"
num_cpus = "1.8.0"
chrono = "0.4.19"
